### ISSUE TITLE
div引入组件,页面useeffect中调用init，存在plug中存在按钮和标题的缓存，会产生重复按钮和标题

### ISSUE THREAD

**Issue by xpqxpxp** [foginn/Graphix#6]

**Comment by manifoldspace** [comment]
init 不能重复执行

**Comment by xiaosongxiaosong** [comment]
@QuadrantIV 
“一个轻量级、可插拔、OOP 式图形编辑器开发引擎”，这个思路很棒
有一点小问题，我看了下 graphix-engine 的代码，这部分实现有两个问题：
一是缺少 init 对应的销毁方法，进行释放资源和删除 dom 节点等操作
二是挂载节点是自己来生成的，id 也是写死的，可以考虑做成传递进来的
